#!/bin/bash

exec 2>&1

if [ -n "${SS_CONFIG}" ]; then
    if [ -z "${SS_MODULE}" ]; then
        echo "Warning: SS_MODULE is empty, default to ss-server!"
        SS_MODULE="ss-server"
    fi
    echo -e  "starting Shadowsocks...  command: ${SS_MODULE} ${SS_CONFIG}"
    exec chpst -u shadowsocks ${SS_MODULE} ${SS_CONFIG}
else
    echo "Shadowsocks not started."
    exec sv stop shadowsocks
    exit 0
fi
